name: Send webmentions

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 min (UTC)
  workflow_dispatch: # allow manual run

jobs:
  ping-webmention:
    runs-on: ubuntu-latest
    steps:
      - name: Send webmentions
        env:
          TOKEN: ${{ secrets.WEBMENTION_TOKEN }}
          FEED_URL: https://blog.jamesandrewscoulter.com/feed.xml
        run: |
          set -euo pipefail
          curl -fsS -X POST \
            --data-urlencode "token=${TOKEN}" \
            --data-urlencode "limit=1" \
            --data-urlencode "url=${FEED_URL}" \
            https://webmention.app/check
